name: Documentation
on:
  push:
    branches:
    - master
    - main
  pull_request:
    branches:
    - master
    - main

jobs:
  build:
    name: Build on commit
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6.9

      - name: Caching
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles("setup.py") }}-${{ hashFiles("requirements.txt") }}

      - name: Install dependencies
        run: |
          python -m pip install -e .
          python -m pip install -e ".[docs]"

      - name: Deploy documentation
        run: mkdocs gh-deploy --force